// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUfGc70EC9junsEHTv0tihtQhpZQmOrZM',
    appId: '1:608078350883:web:99e73b6b0cf2bdc684ff96',
    messagingSenderId: '608078350883',
    projectId: 'adoptplace',
    authDomain: 'adoptplace.firebaseapp.com',
    storageBucket: 'adoptplace.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX9u2fYpkcR6wFUaHr7Fi9K6PRN0E5fXI',
    appId: '1:608078350883:android:092085247467161884ff96',
    messagingSenderId: '608078350883',
    projectId: 'adoptplace',
    storageBucket: 'adoptplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvS4gNiG5np7gc4eDk99k98tDqxX88ebg',
    appId: '1:608078350883:ios:d7768703cc09a8ad84ff96',
    messagingSenderId: '608078350883',
    projectId: 'adoptplace',
    storageBucket: 'adoptplace.firebasestorage.app',
    iosBundleId: 'com.example.adoptPlace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvS4gNiG5np7gc4eDk99k98tDqxX88ebg',
    appId: '1:608078350883:ios:d7768703cc09a8ad84ff96',
    messagingSenderId: '608078350883',
    projectId: 'adoptplace',
    storageBucket: 'adoptplace.firebasestorage.app',
    iosBundleId: 'com.example.adoptPlace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUfGc70EC9junsEHTv0tihtQhpZQmOrZM',
    appId: '1:608078350883:web:5559c1894bd74e5384ff96',
    messagingSenderId: '608078350883',
    projectId: 'adoptplace',
    authDomain: 'adoptplace.firebaseapp.com',
    storageBucket: 'adoptplace.firebasestorage.app',
  );
}
